import { Inter } from 'next/font/google';
import './globals.css';

/*
  FEEDBACK: En la aplicación se esta usando la tipografía Outfit, pero no se esta importando
  en ningún lado. Los computadores solo tienen las tipografías que los usuarios tienen instaladas
  por lo que si se usa una y el usuario no la tiene instalada, se mostrará cualquiera por defecto.
  Para solucionar esto, se debe instalar la tipografía. El estándar en este momento es hacerlo
  desde https://fonts.google.com/ y Next.js ya tiene una forma de implementarlo, de la siguiente
  manera:

  // Se importa la tipografía
  import { Outfit } from 'next/font/google';

  // Se declara la tipografía
  const outfit = Outfit({ subsets: ["latin"] });

  // Se asocia la tipografía a la etiqueta `body` para que quede general
  <body className={outfit.className}>{children}</body>

  Más información: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
*/
const inter = Inter({ subsets: ['latin'] });

/*
  FEEDBACK: Cuando estes presentando pruebas técnicas para una empresa, trata de fijarte en los detalles
  y no dejar cosas genéricas como lo sigueinte, son tonteras, pero como revisor de la prueba, me fijare
  en si el desarrollador se dio el tiempo de notar los pequeños detalles y esta enfocado en el proyecto
  y no haciendo esto de manera genérica. Pon el nombre de la empresa o el proyecto que te dieron.
*/
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
